// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Classes } from "./Classes";
import type { Types } from "./Types";

export interface Transformation { transformedID: string, transformedName: string, transformedClass: Classes, transformedType: Types, transformedSuperAttack: string, transformedEZASuperAttack: string | null, transformedUltraSuperAttack: string | null, transformedEZAUltraSuperAttack: string | null, transformedPassive: string, transformedEZAPassive: string | null, transformedActiveSkill: string | null, transformedActiveSkillCondition: string | null, transformedLinks: Array<string>, transformedImageURL: string, }